# Generated by Django 3.2.10 on 2021-12-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('guid', models.IntegerField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('category', models.JSONField()),
                ('description', models.CharField(max_length=2000)),
                ('pubDate', models.TimeField()),
                ('updateDate', models.TimeField()),
            ],
        ),
    ]
