# Generated by Django 3.2.10 on 2021-12-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pubDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='updateDate',
            field=models.CharField(max_length=50),
        ),
    ]
