# Generated by Django 3.2.10 on 2021-12-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0002_auto_20211225_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pubDate',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='updateDate',
            field=models.TimeField(),
        ),
    ]
