# Generated by Django 3.2.10 on 2021-12-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0003_auto_20211225_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='data',
            name='guid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='pubDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='updateDate',
            field=models.CharField(max_length=50),
        ),
    ]
