# Generated by Django 3.2.10 on 2021-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0004_auto_20211225_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
