# Generated by Django 3.2.10 on 2021-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0005_alter_data_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='guid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
