# Generated by Django 4.0 on 2021-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0006_auto_20211226_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='category',
        ),
        migrations.AddField(
            model_name='data',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='datas', to='webscrawler.Category'),
        ),
    ]
