# Generated by Django 4.0 on 2021-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0007_category_remove_data_category_data_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pubDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='updateDate',
            field=models.DateTimeField(),
        ),
    ]
