# Generated by Django 4.0 on 2021-12-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0008_alter_data_pubdate_alter_data_updatedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='updateDate',
            new_name='updated',
        ),
    ]
