# Generated by Django 4.0 on 2021-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0009_rename_updatedate_data_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='categories',
        ),
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
