# Generated by Django 4.0 on 2021-12-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrawler', '0011_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='category',
            new_name='categories',
        ),
    ]
